### ISSUE TITLE
Add an option to resume from a given date until the present

### ISSUE THREAD

**Issue by miketaylr** [mozilla/tsci#100]
This will be a helpful bandaid fix until #75 is done, but possibly useful for other types of things.

Essentially, I want to be able to give this script a particular date in the past and have it continue to request weeks until it hits the most recent possible week. I've had to do this when hitting #75, and it's annoying to then have to keep requesting new months every few hours until it's done. Something like `--continue` or `--until-today` or whatever would be much nicer.

**Comment by hackhnaton1994** [comment]
Thank you I will Do mike i will sent u id token Add you Gmail...all  issue i wil update to you
At my Gmail founderhackhnaton@gmail.com
