### ISSUE TITLE
Filter out Firefox Preview data

### ISSUE THREAD

**Issue by miketaylr** [mozilla/tsci#101]
It's not a release product and is likely contributing to a lot of noise. Let's filter it out for now and we can add it back in later.

Maybe it's interesting to consider a way to configure this, a lot is hard-coded right now. Dunno if we want to tackle that in this bug or wait until #84 happens.

**Comment by hackhnaton1994** [comment]
malaysia speak : Project saya hancur macamana saya perlu kembalikan dana ethereum Saya

**Comment by hackhnaton1994** [comment]
https://api.etherscan.io/api?module=account&action=balance&address=0xddbd2b932c763ba5b1b7ae3b362eac3e8d40121a&tag=latest&apikey=YourApiKeyToken
