### ISSUE TITLE
Explore alternate methods to get this running in automation

### ISSUE THREAD

**Issue by miketaylr** [mozilla/tsci#115]
My attempt to fix #75 turned out to hit the history ceiling in the same place (starting in January 2019, around April 28, 2018). So copying a sheet from one document to another does not really save history entries the way I had theorized. 

A few different options on how we can fix this:

* fetch weekly data in one document, but only copy over the summary to the "master" document (with a link to the original document). The "master" doc would then just be a chart, summary, and formula sheet.

* have the script clone documents at some predictable interval (every 4 weeks?) and return the ID of the new document. That could be consumed by a web API, or read from disk and be used to generate a link to an iframe. 

* stand up a redirect service that always points to the most recent cloned document (similar to previous idea), based on some stored value of the latest correct ID.

* ...something else? The first seems simplest to attempt .

**Comment by karlcow** [comment]
https://developers.google.com/apps-script/guides/jdbc#read_from_the_database
https://webapps.stackexchange.com/questions/42906/connect-with-database-and-fetch-data-to-google-spreadsheet

Also as a test, I took a ~4Mo csv file with 36635 rows and 18 columns.
And made an import

This was the result of the history. 1 entry created only.

<img width="301" alt="Capture d’écran 2019-09-27 à 12 00 02" src="https://user-images.githubusercontent.com/505230/65738866-5bfbae00-e11e-11e9-9159-bc3af0741321.png">

**Comment by miketaylr** [comment]
@karlcow I think your suggestion here is to dump the data to mysql and read it into the spreadsheet? I think that's a good solution, probably after we fix this issue.

**Comment by karlcow** [comment]
the solution is whatever the source, the import should be only **one** for a full data set, instead of recording each individual data one by one.
