### ISSUE TITLE
Switch from Tranco to the Trexa list

### ISSUE THREAD

**Issue by past** [mozilla/tsci#117]
I had a conversation about the merits of the list that the OpenWPM work is using and dzeber and mlopatka convinced me that the latter would be a better fit for our purposes. The OpenWPM project has a CSV file they publish so it should be pretty straightforward to consume that one instead. Could even make the list selection a configurable parameter for extra brownie points.

**Comment by miketaylr** [comment]
@past can you provide pointers to the Trexa list?

**Comment by past** [comment]
I believe they are [here](https://github.com/mozilla/crawl-prep/tree/master/lists), but they don't appear to be automatically generated as I thought.

**Comment by past** [comment]
What I meant to say is that they don't seem to be publishing any updates to the list in that repo.

**Comment by past** [comment]
Here is the proposed algorithm:

1. Fetch the Tranco list as we do currently.
2. Fetch the Alexa list for the same date from the [archive](https://toplists.net.in.tum.de/archive/alexa/) (or directly from [AWS](http://s3.amazonaws.com/alexa-static/top-1m.csv.zip) if that date is missing or returns an error).
3. Run the (ported to JS) merge algorithm from [list_merge.py](https://github.com/mozilla/crawl-prep/blob/master/list_merge.py).
4. Store the resulting list locally as we currently do.

**Comment by miketaylr** [comment]
New plan: we'll just grab the list from https://github.com/mozilla/trexa-service, which is set to make create and serve a daily list.

**Comment by miketaylr** [comment]
In theory we can get rid of `fetchListID` and just update the following URI:

https://github.com/mozilla/tsci/blob/bbd25a71ce8c9de608788b4bf1f3f12577a1386b/tranco.js#L156
