### ISSUE TITLE
Consider breaking up Google properties

### ISSUE THREAD

**Issue by miketaylr** [mozilla/tsci#61]
In my chat with @andreasbovens he suggested (not as a "release blocker") that we consider breaking up Google properties. Right now google.com is contributing ~151/180 points of the TSCI and he said it might be interesting to see if those are coming from gmail, maps, etc.

We talked about weighting them differently, and I don't know if we have a great way to do that. We could possibly use Google Trends? Or, we can treat the weight the same and just have visibility into the distribution.

**Comment by miketaylr** [comment]
Maybe another way to think about this would be to graph a line for the TSCI - Google...

**Comment by past** [comment]
I'm skeptical about this as there are both a number of technical difficulties to implement, but also not a lot of value since the numbers are small enough that you can eyeball the results page and get a sense of which properties are most prominent.

On the technical side there is the matter of getting a proper list and also finding a way to accurately determine the URLs that map to a particular property (mail.google.com, but also google.com/maps). Tranco is supposedly offering custom lists, but I have never managed to make it work in my testing.

**Comment by adamopenweb** [comment]
Can we use[this list](https://s3-us-west-1.amazonaws.com/umbrella-static/index.html) (or similar) to determine what value our top 500 site list values are (relatively) and where the Google sub-domains fall in-between? 

If the Google sub-domains are lower than 500, we exclude from TSCI. If they are in the top 500 we use this relative positioning to assign a weight to these bugs.

**Comment by past** [comment]
Let's look at a concrete example. [Here](https://docs.google.com/spreadsheets/d/1p-KS34FtrpGkUgwltYdRle3u8oiiCSOFbPy_jH5L_ig/) are the google matches in the top-500 from that list. 
- mail.google.com is at #170. I see 2 related bugzilla entries and 3 webcompat ones in 7/14 (I'm not even counting the duplicates).
- maps.googleapis.com is at #305 (not maps.google.com!). I see 2 bugzilla and 1 webcompat reports (again, ignoring dupes).
- docs.google.com is at #315. I see 2 bugzilla and 3 webcompat entries (w/o dupes).

Not counting these in the top spot in our chart will bring google's score for that day from 86.25 to less than 73.31 (depending on the number of dupes).

calendar.google.com does not appear in the top 500, but we do have 1 bug in bugzilla with 1 dupe. That means that overall, breakage in Gcal contributes 2 points to TSCI, whereas breakage in GMail contributes less than 0.03, GMaps less than 0.01 and GDocs less than 0.02.

What is the value that we get from this change?

**Comment by hackhnaton1994** [comment]
Check windows sofware couple with microsoff i need to bug ig

**Comment by miketaylr** [comment]
Having gotten some experience with the TSCI, I think we can close this. I agree with @past's comment that there isn't a ton of value gained by moving towards this idea.
