### ISSUE TITLE
Consider weighting bugs

### ISSUE THREAD

**Issue by miketaylr** [mozilla/tsci#62]
If we have a Layout P3 bug on google.com, should it be considered equal to a "WebCompat Priority: P1" or a Layout P1 bug?

It feels like we aren't creating an incentive to fix the higher priority bugs by having equal weights for all bugs.

**Comment by past** [comment]
The priority set by the bug component triage owner will reflect the priorities of that team and it seems to me that we should not couple this with what is important for web compatibility. Say for example that a team is focusing on performance and decides to only make related bugs P1/P2. That doesn't mean that the compatibility need isn't there, just that their priorities are different right now. I would expect product priorities to be informed by TSCI, which could change the bug component prioritization, but if we make TSCI automatically reflect the triage owner's decisions, then there is no additional check or value from TSCI.

webcompat:p1 would be a useful weighting factor, but there is a chicken-and-egg problem here: we discussed using TSCI to determine webcompat:p1, so which should come first?

I'm of the opinion that we need to be more data-driven in our prioritization, so starting from user signal (TSCI) to get to bug prioritization seems like the right approach to me.

**Comment by miketaylr** [comment]
Agreed, let's leave it as is.
