### ISSUE TITLE
Extra row beyond the list limit

### ISSUE THREAD

**Issue by miketaylr** [mozilla/tsci#69]
We have a some bug data being gathered and displayed below the last list item. I'm not sure when this happened, but it's on the master branch.

https://docs.google.com/spreadsheets/d/1VS0IIni01KoAnYUXoXMD--yId5tgGkyHIcQ18ghJTdM/edit?usp=sharing

(it doesn't seem like a huge deal, it doesn't skew any of the results -- just looks broken)

**Comment by past** [comment]
I consistently see 3 rows in my tests, which led me to believe that it is the addition of `ignoredDomains` that caused it. I think we loop over the entire set of the bugzilla/webcompat arrays when filling the spreadsheet, instead of the requested `listSize`.

**Comment by miketaylr** [comment]
Yeah, I don't doubt I missed some of the math when we added `ignoredDomains`. WHOSE IDEA WAS THAT.

**Comment by miketaylr** [comment]
Oh, I think I have a hunch on what the bug is. Right now `ignoredDomains` is 3 items long. We just assume we should offset the requested list by 3, because those 3 will get removed. I suspect if the list doesn't include all 3 domains (only 2, for example), then the `listSize` will be off by one. For a regular 500 run, this won't be an issue but for smaller runs it can appear. 

We could fix this by counting any applied list mutations and using that as the offset, rather than just `ignoredDomains.length`. Not a high priority issue, but worth fixing.

(at least, this is my current theory)

**Comment by miketaylr** [comment]
(or we could just clamp the modified CSV to `config.listSize`, whether it was modified or not)

**Comment by miketaylr** [comment]
This run w/ 200 confirms we don't run into this bug for big lists: https://docs.google.com/spreadsheets/d/1CJCeSp_S4Kq1_Rfplq3tod3C90EWD6fSk3ccbvL0Djg/edit?usp=sharing

**Comment by hackhnaton1994** [comment]
https://www.google.com/url?sa=t&source=web&rct=j&url=https://m.facebook.com/&ved=2ahUKEwiIpueomtjjAhVBvY8KHTNXCzwQFjAAegQIAxAD&usg=AOvVaw34tVpM9makLRzsFbubYQeh
Somebody Change my Website www.facebook.com its my facebook
Thanks feedback.i get all my Website. why Her have run my Real system
And give me

**Comment by hackhnaton1994** [comment]
If u know mike im satoshinakamoto no 2 open soucre.. malaysia
