### ISSUE TITLE
Add line for TSCI-D(esktop)

### ISSUE THREAD

**Issue by miketaylr** [mozilla/tsci#82]
Similar to #68

**Comment by miketaylr** [comment]
Rather than add yet another handful of columns, we could replace the TSCI with TSCI-D and then just do math to compute the total from TSCI-D and TSCI-M.

**Comment by past** [comment]
Since TSCI-M is (mobile-only + gecko), I would expect TSCI-D to be (desktop-only + gecko), so how would you calculate TSCI which is (desktop-only + mobile-only + gecko) from these two?

**Comment by miketaylr** [comment]
Magic

(actually no, you're right it won't work)

**Comment by miketaylr** [comment]
Otherwise we could split out Core bugs from the other 2, but that doesn't do anything for us in terms of "saving columns".

**Comment by past** [comment]
I don't mind either way, I think most people will only look at the graph anyway. Maybe there is a value in splitting everything out in that spikes can be more accurately attributed to their cause.
